version: '3.6'
services:
  # The Application
  mars-rover-mission:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: unless-stopped
    container_name: mars-rover-mission
    working_dir: /var/www/html/www.mars-rover-mission.com/
    volumes:
      - ../../:/var/www/html/www.mars-rover-mission.com
      - ./web/apache/www.mars-rover-mission.com.conf:/etc/apache2/sites-enabled/www.mars-rover-mission.com.conf
    ports:
      - 80:80

  mars-mysql:
    image: mysql:5.7
    container_name: mars-mysql
    restart: unless-stopped
    volumes:
      - mars-mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=mars"
      - "MYSQL_USER=mars"
      - "MYSQL_PASSWORD=DvFEwzKLqrrGF9Yz"
      - "MYSQL_ROOT_PASSWORD=XgkJB%]9dHd2@FFL"
    ports:
      - "3306:3306"

volumes:
  mars-mysql:
    driver: local
